#  Copyright (c) 2023 - All rights reserved.
#  Created by Curtis Poon for PROCTECH 4IT3/SEP 6IT3.
#  SoA Notice: I Curtis Poon, 400263978 certify that this material is my original work.
#  I certify that no other person's work has been used without due acknowledgement.
#  I have also not made my work available to anyone else without their due acknowledgement.

# Generated by Django 4.2 on 2023-04-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20)),
                ('ipType', models.CharField(max_length=10)),
                ('contCode', models.CharField(max_length=10)),
                ('contName', models.CharField(max_length=30)),
                ('countryCode', models.CharField(max_length=10)),
                ('countryName', models.CharField(max_length=30)),
                ('regCode', models.CharField(max_length=10)),
                ('regName', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=30)),
                ('zip', models.CharField(max_length=10)),
            ],
        ),
    ]
