#  Copyright (c) 2023 - All rights reserved.
#  Created by Curtis Poon for PROCTECH 4IT3/SEP 6IT3.
#  SoA Notice: I Curtis Poon, 400263978 certify that this material is my original work.
#  I certify that no other person's work has been used without due acknowledgement.
#  I have also not made my work available to anyone else without their due acknowledgement.

# Generated by Django 4.2 on 2023-04-15 22:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='airQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carbon', models.CharField(max_length=30)),
                ('nox', models.CharField(max_length=30)),
                ('o3', models.CharField(max_length=30)),
                ('so2', models.CharField(max_length=30)),
                ('fine', models.CharField(max_length=30)),
                ('ultra', models.CharField(max_length=30)),
                ('usa', models.CharField(max_length=5)),
                ('eu', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='general',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last', models.DateTimeField()),
                ('tod', models.CharField(max_length=20)),
                ('cloud', models.CharField(max_length=5)),
                ('condition', models.ImageField(upload_to='')),
                ('uv', models.CharField(max_length=5)),
                ('vkm', models.CharField(max_length=5)),
                ('vm', models.CharField(max_length=5)),
                ('pmb', models.CharField(max_length=10)),
                ('piw', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempc', models.CharField(max_length=5)),
                ('tempf', models.CharField(max_length=5)),
                ('hum', models.CharField(max_length=5)),
                ('flc', models.CharField(max_length=5)),
                ('flf', models.CharField(max_length=5)),
                ('wskm', models.CharField(max_length=10)),
                ('wsm', models.CharField(max_length=10)),
                ('wd', models.CharField(max_length=5)),
                ('wdd', models.CharField(max_length=5)),
                ('epmm', models.CharField(max_length=5)),
                ('epin', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='weatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=30)),
                ('local', models.DateTimeField()),
                ('lat', models.CharField(max_length=10)),
                ('long', models.CharField(max_length=10)),
            ],
        ),
    ]
