# Generated by Django 4.2 on 2023-04-15 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_airquality_general_temp_weatherdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weatherdata',
            old_name='local',
            new_name='localtime',
        ),
        migrations.RenameField(
            model_name='weatherdata',
            old_name='time',
            new_name='timezone',
        ),
    ]
