#  Copyright (c) 2023 - All rights reserved.
#  Created by Curtis Poon for PROCTECH 4IT3/SEP 6IT3.
#  SoA Notice: I Curtis Poon, 400263978 certify that this material is my original work.
#  I certify that no other person's work has been used without due acknowledgement.
#  I have also not made my work available to anyone else without their due acknowledgement.

# Generated by Django 4.2 on 2023-04-15 22:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0003_rename_local_weatherdata_localtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general',
            name='last',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='localtime',
            field=models.CharField(max_length=30),
        ),
    ]
