# Generated by Django 4.2 on 2023-04-15 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_local_weatherdata_localtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general',
            name='last',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='localtime',
            field=models.CharField(max_length=30),
        ),
    ]
