# Generated by Django 4.2 on 2023-04-15 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_general_last_alter_weatherdata_localtime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weatherdata',
            old_name='localtime',
            new_name='localt',
        ),
    ]
