#  Copyright (c) 2023 - All rights reserved.
#  Created by Curtis Poon for PROCTECH 4IT3/SEP 6IT3.
#  SoA Notice: I Curtis Poon, 400263978 certify that this material is my original work.
#  I certify that no other person's work has been used without due acknowledgement.
#  I have also not made my work available to anyone else without their due acknowledgement.

# Generated by Django 4.2 on 2023-04-15 23:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0005_rename_localtime_weatherdata_localt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weatherdata',
            old_name='long',
            new_name='lon',
        ),
    ]
