# Generated by Django 4.2 on 2023-04-15 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_localtime_weatherdata_localt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weatherdata',
            old_name='long',
            new_name='lon',
        ),
    ]
