# Generated by Django 4.2 on 2023-04-16 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_long_weatherdata_lon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='general',
            old_name='condition',
            new_name='cond',
        ),
    ]
