# Generated by Django 4.2 on 2023-04-16 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_condition_general_cond'),
    ]

    operations = [
        migrations.RenameField(
            model_name='general',
            old_name='last',
            new_name='lst',
        ),
    ]
