#  Copyright (c) 2023 - All rights reserved.
#  Created by Curtis Poon for PROCTECH 4IT3/SEP 6IT3.
#  SoA Notice: I Curtis Poon, 400263978 certify that this material is my original work.
#  I certify that no other person's work has been used without due acknowledgement.
#  I have also not made my work available to anyone else without their due acknowledgement.

# Generated by Django 4.2 on 2023-04-16 17:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0007_rename_condition_general_cond'),
    ]

    operations = [
        migrations.RenameField(
            model_name='general',
            old_name='last',
            new_name='lst',
        ),
    ]
