#  Copyright (c) 2023 - All rights reserved.
#  Created by Curtis Poon for PROCTECH 4IT3/SEP 6IT3.
#  SoA Notice: I Curtis Poon, 400263978 certify that this material is my original work.
#  I certify that no other person's work has been used without due acknowledgement.
#  I have also not made my work available to anyone else without their due acknowledgement.

# Generated by Django 4.2 on 2023-04-17 01:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0008_rename_last_general_lst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdata',
            name='country',
            field=models.CharField(max_length=30),
        ),
    ]
